<a href="https://colab.research.google.com/github/Tissyjohnson/DSA_Class_Activities/blob/main/Numpy_Pandas_Tissy_Johnson.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
# Create array with values from 10 to 49 (inclusive)
import numpy as np
arr = np.arange(10, 50)
matrix = arr.reshape(4, 10)
last_col = matrix[:, -1]
print("Array from 10 to 49:\n", arr)
print("\nReshaped 4x10 matrix:\n", matrix)
print("\nLast column:\n", last_col)


Array from 10 to 49:
 [10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]

Reshaped 4x10 matrix:
 [[10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]]

Last column:
 [19 29 39 49]


In [2]:
# Create two 3×3 matrices
import numpy as np
A = np.full((3, 3), 5)
B = np.arange(1, 10).reshape(3, 3)
add_result = A + B
mul_result = A * B
transpose_result = mul_result.T

print("Matrix A (all 5s):\n", A)
print("\nMatrix B (1 to 9):\n", B)
print("\nAddition Result:\n", add_result)
print("\nElement-wise Multiplication Result:\n", mul_result)
print("\nTranspose of Multiplication Result:\n", transpose_result)


Matrix A (all 5s):
 [[5 5 5]
 [5 5 5]
 [5 5 5]]

Matrix B (1 to 9):
 [[1 2 3]
 [4 5 6]
 [7 8 9]]

Addition Result:
 [[ 6  7  8]
 [ 9 10 11]
 [12 13 14]]

Element-wise Multiplication Result:
 [[ 5 10 15]
 [20 25 30]
 [35 40 45]]

Transpose of Multiplication Result:
 [[ 5 20 35]
 [10 25 40]
 [15 30 45]]


In [3]:
# Create array of 15 random integers between 10 and 100
import numpy as np
arr = np.random.randint(10, 101, size=15)
replaced_arr = arr.copy()
replaced_arr[replaced_arr > 50] = -1
count_replaced = np.sum(arr > 50)

print("Original Array:\n", arr)
print("\nModified Array:\n", replaced_arr)
print("\nNumber of values replaced:", count_replaced)


Original Array:
 [49 83 35 45 44 83 37 92 32 97 36 24 76 15 89]

Modified Array:
 [49 -1 35 45 44 -1 37 -1 32 -1 36 24 -1 15 -1]

Number of values replaced: 6


In [26]:
import numpy as np
arr = np.random.rand(5, 4)
print("Original Array:\n", arr)
row_sums = arr.sum(axis=1)
max_row_index = np.argmax(row_sums)
print("\nRow sums:", row_sums)
print("Row with maximum sum is:", max_row_index)
normalized_arr = np.zeros_like(arr)
for i, row in enumerate(arr):
    row_min, row_max = row.min(), row.max()
    normalized_arr[i] = (row - row_min) / (row_max - row_min)

print("\nNormalized Array:\n", normalized_arr)


Original Array:
 [[0.58863885 0.09762703 0.10083363 0.65706128]
 [0.34723027 0.79788353 0.11837491 0.82147748]
 [0.1763669  0.98875945 0.24303128 0.46377252]
 [0.60950441 0.58918769 0.91310413 0.90172155]
 [0.88237091 0.76764643 0.95092306 0.62563041]]

Row sums: [1.44416078 2.08496619 1.87193015 3.01351777 3.22657081]
Row with maximum sum is: 4

Normalized Array:
 [[0.87769353 0.         0.00573186 1.        ]
 [0.32549357 0.96644308 0.         1.        ]
 [0.         1.         0.08205931 0.35377678]
 [0.06272211 0.         1.         0.96485951]
 [0.78926006 0.43657926 1.         0.        ]]


In [4]:
import numpy as np
arr = np.array([1, 3, 5, 3, 7, 9, 1, 5, 5])
# Find all unique elements
unique_elements = np.unique(arr)

# Find duplicates (elements with count > 1)
unique, counts = np.unique(arr, return_counts=True)
duplicates = unique[counts > 1]

print("Unique elements:", unique_elements)
print("Duplicates:", duplicates)


Unique elements: [1 3 5 7 9]
Duplicates: [1 3 5]


In [5]:
# Create a 6×6 NumPy array with values from 1 to 36.
import numpy as np
arr = np.arange(1, 37).reshape(6, 6)
submatrix = arr[1:5, 1:5]
even_numbers = submatrix[submatrix % 2 == 0]

print("Original 6x6 Matrix:\n", arr)
print("\nMiddle 4x4 Submatrix:\n", submatrix)
print("\nEven numbers from Submatrix:\n", even_numbers)


Original 6x6 Matrix:
 [[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]
 [25 26 27 28 29 30]
 [31 32 33 34 35 36]]

Middle 4x4 Submatrix:
 [[ 8  9 10 11]
 [14 15 16 17]
 [20 21 22 23]
 [26 27 28 29]]

Even numbers from Submatrix:
 [ 8 10 14 16 20 22 26 28]


In [6]:
# Generate array of shape (3, 4) with values 0 to 11
import numpy as np
arr = np.arange(12).reshape(3, 4)
reshaped_2x6 = arr.reshape(2, 6)
flattened = arr.flatten()
reshaped_4x3 = flattened.reshape(4, 3)

print("Original (3x4) array:\n", arr)
print("\nReshaped (2x6) array:\n", reshaped_2x6)
print("\nFlattened 1D array:\n", flattened)
print("\nReshaped back to (4x3):\n", reshaped_4x3)


Original (3x4) array:
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

Reshaped (2x6) array:
 [[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]

Flattened 1D array:
 [ 0  1  2  3  4  5  6  7  8  9 10 11]

Reshaped back to (4x3):
 [[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [7]:
# Create an array: a = np.array([[1, 2], [3, 4]])
import numpy as np
a = np.array([[1, 2],
              [3, 4]])

a_new_row = np.vstack([a, [5, 6]])
a_new_col = np.column_stack([a_new_row, [7, 8, 9]])

print("Original array:\n", a)
print("\nAfter appending row [5, 6]:\n", a_new_row)
print("\nAfter appending column [7, 8, 9]:\n", a_new_col)


Original array:
 [[1 2]
 [3 4]]

After appending row [5, 6]:
 [[1 2]
 [3 4]
 [5 6]]

After appending column [7, 8, 9]:
 [[1 2 7]
 [3 4 8]
 [5 6 9]]


In [8]:
#Join them into a single array
import numpy as np
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
c = np.array([7, 8, 9])
joined = np.concatenate([a, b, c])
matrix = joined.reshape(3, 3)
diagonal = np.diag(matrix)

print("Joined array:\n", joined)
print("\nReshaped 3x3 matrix:\n", matrix)
print("\nDiagonal elements:", diagonal)


Joined array:
 [1 2 3 4 5 6 7 8 9]

Reshaped 3x3 matrix:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]

Diagonal elements: [1 5 9]


In [9]:
# Create array of integers from 1 to 20
import numpy as np
arr = np.arange(1, 21)
divisible = arr[(arr % 3 == 0) | (arr % 5 == 0)]
count = divisible.size

print("Original array:\n", arr)
print("\nValues divisible by 3 or 5:\n", divisible)
print("\nCount:", count)


Original array:
 [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]

Values divisible by 3 or 5:
 [ 3  5  6  9 10 12 15 18 20]

Count: 9


PANDAS

In [10]:
# Load the Titanic dataset and display the first 10 rows.
import seaborn as sns
import pandas as pd
titanic = sns.load_dataset("titanic")

print(titanic.head(10))


   survived  pclass     sex   age  sibsp  parch     fare embarked   class  \
0         0       3    male  22.0      1      0   7.2500        S   Third   
1         1       1  female  38.0      1      0  71.2833        C   First   
2         1       3  female  26.0      0      0   7.9250        S   Third   
3         1       1  female  35.0      1      0  53.1000        S   First   
4         0       3    male  35.0      0      0   8.0500        S   Third   
5         0       3    male   NaN      0      0   8.4583        Q   Third   
6         0       1    male  54.0      0      0  51.8625        S   First   
7         0       3    male   2.0      3      1  21.0750        S   Third   
8         1       3  female  27.0      0      2  11.1333        S   Third   
9         1       2  female  14.0      1      0  30.0708        C  Second   

     who  adult_male deck  embark_town alive  alone  
0    man        True  NaN  Southampton    no  False  
1  woman       False    C    Cherbourg   yes

In [11]:
# Find the number of missing values in each column.
import seaborn as sns
import pandas as pd
titanic = sns.load_dataset("titanic")

missing_values = titanic.isnull().sum()

print("Missing values per column:\n", missing_values)


Missing values per column:
 survived         0
pclass           0
sex              0
age            177
sibsp            0
parch            0
fare             0
embarked         2
class            0
who              0
adult_male       0
deck           688
embark_town      2
alive            0
alone            0
dtype: int64


In [12]:
# Find the percentage of passengers who survived, grouped by gender.
import seaborn as sns
import pandas as pd
titanic = sns.load_dataset("titanic")
survival_by_gender = titanic.groupby("sex")["survived"].mean() * 100

print("Survival percentage by gender:\n", survival_by_gender)


Survival percentage by gender:
 sex
female    74.203822
male      18.890815
Name: survived, dtype: float64


In [13]:
# Find the average, median, and standard deviation of passenger ages.
import seaborn as sns
import pandas as pd
titanic = sns.load_dataset("titanic")
avg_age = titanic["age"].mean()
median_age = titanic["age"].median()
std_age = titanic["age"].std()

print("Average Age:", avg_age)
print("Median Age:", median_age)
print("Standard Deviation of Age:", std_age)


Average Age: 29.69911764705882
Median Age: 28.0
Standard Deviation of Age: 14.526497332334044


In [14]:
# Count how many passengers were in each class (pclass).
import seaborn as sns
import pandas as pd
titanic = sns.load_dataset("titanic")
class_counts = titanic["pclass"].value_counts()

print("Passenger count by class:\n", class_counts)


Passenger count by class:
 pclass
3    491
1    216
2    184
Name: count, dtype: int64


In [25]:
# Show all passengers who were female, under age 18, and survived
import seaborn as sns
import pandas as pd

titanic = sns.load_dataset("titanic")
female_young_survivors = titanic[
    (titanic["sex"] == "female") &
    (titanic["age"] < 18) &
    (titanic["survived"] == 1)
]

print("Female passengers under 18 who survived:\n")
print(female_young_survivors)


Female passengers under 18 who survived:

     survived  pclass     sex    age  sibsp  parch      fare embarked   class  \
9           1       2  female  14.00      1      0   30.0708        C  Second   
10          1       3  female   4.00      1      1   16.7000        S   Third   
22          1       3  female  15.00      0      0    8.0292        Q   Third   
39          1       3  female  14.00      1      0   11.2417        C   Third   
43          1       2  female   3.00      1      2   41.5792        C  Second   
58          1       2  female   5.00      1      2   27.7500        S  Second   
68          1       3  female  17.00      4      2    7.9250        S   Third   
84          1       2  female  17.00      0      0   10.5000        S  Second   
156         1       3  female  16.00      0      0    7.7333        Q   Third   
172         1       3  female   1.00      1      1   11.1333        S   Third   
184         1       3  female   4.00      0      2   22.0250       

In [19]:
# Replace missing age values with the median age.
import seaborn as sns
import pandas as pd

titanic = sns.load_dataset("titanic")

median_age = titanic["age"].median()
print("Median Age used for replacement:", median_age)
titanic["age"] = titanic["age"].fillna(median_age)



Median Age used for replacement: 28.0


In [18]:
# Create a column age_group with values:
import seaborn as sns
import pandas as pd
import numpy as np

titanic = sns.load_dataset("titanic")
titanic["age"] = titanic["age"].fillna(titanic["age"].median())

titanic["age_group"] = np.where(titanic["age"] < 18, "Child",
                        np.where(titanic["age"] <= 60, "Adult", "Senior"))

print(titanic[["age", "age_group"]].head(15))


     age age_group
0   22.0     Adult
1   38.0     Adult
2   26.0     Adult
3   35.0     Adult
4   35.0     Adult
5   28.0     Adult
6   54.0     Adult
7    2.0     Child
8   27.0     Adult
9   14.0     Child
10   4.0     Child
11  58.0     Adult
12  20.0     Adult
13  39.0     Adult
14  14.0     Child


In [20]:
# Display the top 5 passengers who paid the highest fare.
import seaborn as sns
import pandas as pd

titanic = sns.load_dataset("titanic")
top5_fares = titanic.sort_values("fare", ascending=False).head(5)

print("Top 5 passengers who paid the highest fare:\n")
print(top5_fares[["sex", "pclass", "age", "fare", "embarked", "survived"]])


Top 5 passengers who paid the highest fare:

        sex  pclass   age      fare embarked  survived
679    male       1  36.0  512.3292        C         1
258  female       1  35.0  512.3292        C         1
737    male       1  35.0  512.3292        C         1
88   female       1  23.0  263.0000        S         1
438    male       1  64.0  263.0000        S         0


In [21]:
# Find the average fare paid, grouped by both pclass and sex.
import seaborn as sns
import pandas as pd

titanic = sns.load_dataset("titanic")
avg_fare = titanic.groupby(["pclass", "sex"])["fare"].mean()

print("Average fare by class and gender:\n")
print(avg_fare)


Average fare by class and gender:

pclass  sex   
1       female    106.125798
        male       67.226127
2       female     21.970121
        male       19.741782
3       female     16.118810
        male       12.661633
Name: fare, dtype: float64


In [22]:
# Rename columns
import seaborn as sns
import pandas as pd

titanic = sns.load_dataset("titanic")
titanic.rename(columns={"sex": "gender", "fare": "ticket_fare"}, inplace=True)

print(titanic.head())


   survived  pclass  gender   age  sibsp  parch  ticket_fare embarked  class  \
0         0       3    male  22.0      1      0       7.2500        S  Third   
1         1       1  female  38.0      1      0      71.2833        C  First   
2         1       3  female  26.0      0      0       7.9250        S  Third   
3         1       1  female  35.0      1      0      53.1000        S  First   
4         0       3    male  35.0      0      0       8.0500        S  Third   

     who  adult_male deck  embark_town alive  alone  
0    man        True  NaN  Southampton    no  False  
1  woman       False    C    Cherbourg   yes  False  
2  woman       False  NaN  Southampton   yes   True  
3  woman       False    C  Southampton   yes  False  
4    man        True  NaN  Southampton    no   True  


In [23]:
# Count the number of passengers who survived and didn’t survive, grouped by class.
import seaborn as sns
import pandas as pd

titanic = sns.load_dataset("titanic")
survival_counts = titanic.groupby(["pclass", "survived"]).size().unstack()

print("Passenger survival counts by class:\n")
print(survival_counts)


Passenger survival counts by class:

survived    0    1
pclass            
1          80  136
2          97   87
3         372  119


In [24]:
# Find the average age of passengers grouped by both class and gender.
import seaborn as sns
import pandas as pd

titanic = sns.load_dataset("titanic")
titanic["age"] = titanic["age"].fillna(titanic["age"].median())
avg_age = titanic.groupby(["pclass", "sex"])["age"].mean()

print("Average age of passengers grouped by class and gender:\n")
print(avg_age)


Average age of passengers grouped by class and gender:

pclass  sex   
1       female    33.978723
        male      38.995246
2       female    28.703947
        male      30.512315
3       female    23.572917
        male      26.911873
Name: age, dtype: float64
